services:
  # quality check service
  quality:
    build:
      context: .
      target: quality
    volumes:
      - .:/app

  # development service
  dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npx", "tsx", "src/server.ts"]
    depends_on:
      quality:
        condition: service_completed_successfully

  # production service
  prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=prod
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]
    depends_on:
      quality:
        condition: service_completed_successfully

# testing service
  test:
    build:
      context: .
      target: testing
    environment:
      - NODE_ENV=test
    ports:
      - "3000:3000"
    command: ["npm", "test"]
    depends_on:
      quality:
        condition: service_completed_successfully
