services:
  # Quality check service
  quality:
    build:
      context: .
      target: quality
    volumes:
      - .:/app

  # Development service
  dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npx", "tsx", "src/server.ts"]
    depends_on:
      quality:
        condition: service_completed_successfully

  # Production service
  prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]
    depends_on:
      quality:
        condition: service_completed_successfully
