services:
  # Development service
  dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npx", "tsx", "src/server.ts"]

  # Production service
  prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]
